apiVersion: apps/v1
kind: Deployment
metadata:
  name: net-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: net-app
  template:
    metadata:
      labels:
        app: net-app
        version: v-BUILDNUM
    spec:
      containers:
      - name: net-app
        image: sauravsrivastav/web:v1
        ports:
        - containerPort: 80
        resources:
          requests: # minimum resources required
            cpu: 250m
            memory: 64Mi
          limits: # maximum resources allocated
            cpu: 500m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: net-app
spec:
  type: LoadBalancer
  selector:
    app: net-app
  ports:
  - port: 80
    targetPort: 80
